package dao;


import static dao.DAOUtility.fermeturesSilencieuses;
import static dao.DAOUtility.initialisationRequetePreparee;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;




import beans.Course;

public class CourseDaoImpl implements CourseDao {

	private DAOFactory daoFactory;
	
	private static final String SQL_SELECT = "SELECT courseID, courseName, courseYear, courseDescription, courseschedule FROM Course ORDER BY courseID";
	private static final String SQL_SELECT_BY_COURSEID = "SELECT courseID, courseName, courseYear, courseDescription, courseschedule FROM Course WHERE courseID = ?";
	private static final String SQL_INSERT = "INSERT INTO Course ( courseName, courseYear, courseDescription, courseschedule) VALUES ( ?, ?, ?, ?)";
	private static final String SQL_DELETE_BY_COURSEID = "DELETE FROM Course WHERE courseID = ?";

	CourseDaoImpl(DAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}
	
	@Override
	public void create(Course course) throws DAOException {
		Connection connexion = null;
		PreparedStatement preparedStatement = null;
		ResultSet autoGeneratedValues = null;

		try {
			connexion = daoFactory.getConnection();
			preparedStatement = initialisationRequetePreparee(connexion,
					SQL_INSERT, true, course.getCourseID(), course.getCourseName(), course.getCourseYear(), course.getDescription(), course.getSchedule());
			int statut = preparedStatement.executeUpdate();
			if (statut == 0) {
				throw new DAOException(
						"Failed to create client. No row added");
			}
			autoGeneratedValues = preparedStatement.getGeneratedKeys();
			if (autoGeneratedValues.next()) {
				course.setCourseID(autoGeneratedValues.getInt(1));
			} else {
				throw new DAOException(
						"Failed to create course in DB, no courseID auto-generated returned.");
			}
		} catch (SQLException e) {
			throw new DAOException(e);
		} finally {
			fermeturesSilencieuses(autoGeneratedValues, preparedStatement,
					connexion);
		}
	}

	@Override
	public Course find(long courseID) throws DAOException {
		return find(SQL_SELECT_BY_COURSEID, courseID);
	}

	@Override
	public List<Course> list() throws DAOException {
		Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        List<Course> courses = new ArrayList<Course>();

        try {
            connection = daoFactory.getConnection();
            preparedStatement = connection.prepareStatement( SQL_SELECT );
            resultSet = preparedStatement.executeQuery();
            while ( resultSet.next() ) {
                courses.add( map( resultSet ) );
            }
        } catch ( SQLException e ) {
            throw new DAOException( e );
        } finally {
            fermeturesSilencieuses( resultSet, preparedStatement, connection );
        }

        return courses;
	}

	@Override
	public void delete(Course course) throws DAOException {
		Connection connexion = null;
        PreparedStatement preparedStatement = null;

        try {
            connexion = daoFactory.getConnection();
            preparedStatement = initialisationRequetePreparee( connexion, SQL_DELETE_BY_COURSEID, true, course.getCourseID() );
            int statut = preparedStatement.executeUpdate();
            if ( statut == 0 ) {
                throw new DAOException( "Failed to delete course, no row deleted." );
            } else {
            	//course.setICourseID( null );
            }
        } catch ( SQLException e ) {
            throw new DAOException( e );
        } finally {
            fermeturesSilencieuses( preparedStatement, connexion );
        }
	}
	
	private Course find( String sql, Object... objets ) throws DAOException {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        Course course = null;

        try {
            /* Récupération d'une connection depuis la Factory */
            connection = daoFactory.getConnection();
            /*
             * Préparation de la requête avec les objets passés en arguments
             * (ici, uniquement un id) et exécution.
             */
            preparedStatement = initialisationRequetePreparee( connection, sql, false, objets );
            resultSet = preparedStatement.executeQuery();
            /* Parcours de la ligne de données retournée dans le ResultSet */
            if ( resultSet.next() ) {
                course = map( resultSet );
            }
        } catch ( SQLException e ) {
            throw new DAOException( e );
        } finally {
            fermeturesSilencieuses( resultSet, preparedStatement, connection );
        }

        return course;
    }
	
	
	private static Course map(ResultSet resultSet) throws SQLException {
		
		Course course = new Course();
		course.setCourseID(resultSet.getInt("courseID"));
		course.setCourseName(resultSet.getString("courseName"));
		course.setCourseYear(resultSet.getInt("courseYear"));
		course.setCourseDescription(resultSet.getString("courseDescription"));
		course.setSchedule(resultSet.getString("schedule"));
		return course;
	}

}
