package dao;

import static dao.DAOUtility.fermeturesSilencieuses;
import static dao.DAOUtility.initialisationRequetePreparee;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.List;

import beans.Group;
import beans.User;



public class UserGroupDaoImpl implements UserGroupDao {

	
	private DAOFactory daoFactory;
	
	private static final String SQL_INSERT = "INSERT INTO user_group (username , groupID) VALUES (? , ?)";
	private static final String SQL_SELECT_USER_GROUPS = "SELECT groupName, groupDescription FROM group WHERE groupID IN (SELECT groupID FROM user_group WHERE username = ?) ORDER BY groupName";
	private static final String SQL_SELECT_GROUP_USERS	 = "SELECT * FROM user WHERE username IN (SELECT username FROM user_group WHERE groupID = ?) ORDER BY username";
	private static final String SQL_DELETE_BY_USERNAME = "DELETE FROM user_group WHERE username = ?";
	private static final String SQL_DELETE_BY_GROUPID = "DELETE FROM user_group WHERE groupID = ?";
	private static final String SQL_DELETE =  "DELETE FROM user_group WHERE username = ? AND groupID = ?";

	UserGroupDaoImpl(DAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}

	@Override
	public void create(int groupID, String username) throws DAOException {
		Connection connexion = null;
		PreparedStatement preparedStatement = null;
		ResultSet autoGeneratedValues = null;

		try {
			connexion = daoFactory.getConnection();
			preparedStatement = initialisationRequetePreparee(connexion,
					SQL_INSERT, true, username, groupID);
			int statut = preparedStatement.executeUpdate();
			if (statut == 0) {
				throw new DAOException(
						"Failed to create user-group association. No row added");
			}
			
		} catch (SQLException e) {
			throw new DAOException(e);
		} finally {
			fermeturesSilencieuses(autoGeneratedValues, preparedStatement,
					connexion);
		}
	}

	@Override
	public void delete(int groupID, String username) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void deleteBygroupID(int groupID) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void deleteByPrivID(String username) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List<User> listGroupUsers(int groupID) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Group> listUserGroups(String username) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}
	
}
